%% Figure 6: Flux comparison of Basic, Isozyme and Integrated ecModels
%
% Workflow
% --------
% 1. Load and calibrate Basic / Isozyme / Integrated models
% 2. Determine maximum growth for each model
% 3. Use Basic maximum growth as common growth state
% 4. Minimize protein requirement + pFBA
% 5. Collapse:
%       _EXP_n  -> parent reaction
%       _REV    -> reverse contribution to parent net flux
% 6. Align common parent reactions
% 7. Retain reactions carrying flux in all three models
% 8. Plot absolute net flux on log scale
% 9. Highlight off-diagonal reactions in both 3D and 2D
% 10. Export flux and correlation tables

clear;
clc;


%% ========================================================================
% 1. Load models
% ========================================================================

project_name = 'eciML1515';

project_path = findECOMAProot;

InitializeECOMAPproject( ...
    project_name, ...
    project_path);


ParameterManagerLocation = fullfile( ...
    findECOMAProot, ...
    project_name, ...
    [project_name 'ParameterManagement.m']);

ParameterManager.getParams( ...
    ParameterManagerLocation);

outputDir = fullfile( ...
    findECOMAProot, ...
    'projects', ...
    project_name, ...
    'analysis', ...
    'StructuralAnalysis');

if ~exist(outputDir, 'dir')
    mkdir(outputDir);
end

fprintf('Output directory:\n%s\n', outputDir);

modelDir = fullfile( ...
    findECOMAProot, ...
    'projects', ...
    project_name, ...
    'models');


load(fullfile( ...
    modelDir, ...
    'eciML1515-integrated.mat'));

load(fullfile( ...
    modelDir, ...
    'eciML1515-isozyme.mat'));

load(fullfile( ...
    modelDir, ...
    'eciML1515-basic.mat'));


%% ========================================================================
% 2. Apply sluice structure
% ========================================================================

T = readtable( ...
    fullfile( ...
        findECOMAProot, ...
        'projects', ...
        project_name, ...
        'calibration', ...
        'data', ...
        'UnconstrainedMaxGrowth.tsv'), ...
    'FileType', 'text', ...
    'ReadRowNames', true);


ex_rxn_list = unique(T.Substrate);

ex_rxn_list = ex_rxn_list( ...
    ~strcmp(ex_rxn_list, 'NaN'));


[eciML1515_integrated, ~] = applySluiceStructure( ...
    eciML1515_integrated, ...
    ex_rxn_list);

[eciML1515_isozyme, ~] = applySluiceStructure( ...
    eciML1515_isozyme, ...
    ex_rxn_list);

[eciML1515_basic, ~] = applySluiceStructure( ...
    eciML1515_basic, ...
    ex_rxn_list);


%% ========================================================================
% 3. Apply calibrated kcat values
% ========================================================================

kcatRepo = KcatRepo.loadMat( ...
    'calibration/eciML1515_kcatRepo.mat');


eciML1515_integrated = kcatRepo.applyToModel( ...
    eciML1515_integrated, ...
    'mSA_ABC_SMF_GAUKS');

eciML1515_integrated = UpdateSmatrix( ...
    eciML1515_integrated);


eciML1515_isozyme = kcatRepo.applyToModel( ...
    eciML1515_isozyme, ...
    'mSA_ABC_SMF_GAUKS');

eciML1515_isozyme = UpdateSmatrix( ...
    eciML1515_isozyme);


eciML1515_basic = kcatRepo.applyToModel( ...
    eciML1515_basic, ...
    'mSA_ABC_SMF_GAUKS');

eciML1515_basic = UpdateSmatrix( ...
    eciML1515_basic);


ecGEMs = {
    eciML1515_integrated
    eciML1515_isozyme
    eciML1515_basic
};


modelNames = {
    'Integrated'
    'Isozyme'
    'Basic'
};


c_source = 'EX_glc__D_e';

bioRxn = 'biomass';


%% ========================================================================
% 4. Determine maximum growth
% ========================================================================

solmaxbio = zeros(3,1);


for i = 1:3

    ecGEMs{i} = setParam( ...
        ecGEMs{i}, ...
        'lb', ...
        c_source, ...
        -10);


    ecGEMs{i}.c(:) = 0;


    ecGEMs{i} = setParam( ...
        ecGEMs{i}, ...
        'obj', ...
        bioRxn, ...
        1);


    sol = solveLP(ecGEMs{i});


    if isempty(sol.x)

        error( ...
            '%s: biomass optimization failed.', ...
            modelNames{i});

    end


    solmaxbio(i) = sol.f;

end


fprintf('\nMaximum biomass:\n');


for i = 1:3

    fprintf( ...
        '%-12s %.8g\n', ...
        modelNames{i}, ...
        solmaxbio(i));

end


%% ========================================================================
% 5. Common growth + protein minimization + pFBA
% ========================================================================

% Use Basic maximum growth as the common feasible growth state

commonGrowth = solmaxbio(3);


fprintf( ...
    '\nCommon growth used for comparison: %.8g\n', ...
    commonGrowth);


flux = cell(3,1);


for i = 1:3

    % Same minimum biomass constraint
    ecGEMs{i} = setParam( ...
        ecGEMs{i}, ...
        'lb', ...
        bioRxn, ...
        commonGrowth);


    % Protein pool as primary objective
    ecGEMs{i}.c(:) = 0;


    ecGEMs{i} = setParam( ...
        ecGEMs{i}, ...
        'obj', ...
        'prot_pool_exchange', ...
        1);


    % Parsimonious flux solution
    sol = solveLP( ...
        ecGEMs{i}, ...
        1);


    if isempty(sol.x)

        error( ...
            '%s: pFBA optimization failed.', ...
            modelNames{i});

    end


    flux{i} = sol.x;


    fprintf( ...
        '%-12s pFBA completed, objective = %.8g\n', ...
        modelNames{i}, ...
        sol.f);

end


%% ========================================================================
% 6. Collapse expanded and irreversible reactions
%
% Examples
% --------
%
% r_1138_EXP_1
% r_1138_EXP_2
% r_1138_REV_EXP_1
%
% become:
%
% r_1138
%
% net flux =
% sum(forward copies) - sum(reverse copies)
% ========================================================================

Tintegrated = aggregateEcFlux( ...
    ecGEMs{1}, ...
    flux{1});


Tisozyme = aggregateEcFlux( ...
    ecGEMs{2}, ...
    flux{2});


Tbasic = aggregateEcFlux( ...
    ecGEMs{3}, ...
    flux{3});


%% ========================================================================
% 7. Align common parent reactions
% ========================================================================

commonRxns = intersect( ...
    Tintegrated.ReactionID, ...
    Tisozyme.ReactionID, ...
    'stable');


commonRxns = intersect( ...
    commonRxns, ...
    Tbasic.ReactionID, ...
    'stable');


[~, idxI] = ismember( ...
    commonRxns, ...
    Tintegrated.ReactionID);


[~, idxZ] = ismember( ...
    commonRxns, ...
    Tisozyme.ReactionID);


[~, idxB] = ismember( ...
    commonRxns, ...
    Tbasic.ReactionID);


% Signed net flux
vIntegrated = Tintegrated.NetFlux(idxI);

vIsozyme = Tisozyme.NetFlux(idxZ);

vBasic = Tbasic.NetFlux(idxB);


fprintf( ...
    '\nCommon aligned parent reactions: %d\n', ...
    numel(commonRxns));


%% ========================================================================
% 8. Retain reactions carrying net flux in ALL three models
% ========================================================================

fluxTol = 1e-8;


active = ...
    abs(vBasic)      > fluxTol & ...
    abs(vIsozyme)    > fluxTol & ...
    abs(vIntegrated) > fluxTol;


commonRxns = commonRxns(active);

vBasic = vBasic(active);

vIsozyme = vIsozyme(active);

vIntegrated = vIntegrated(active);


fprintf( ...
    'Common active parent reactions used for plotting: %d\n', ...
    numel(commonRxns));


%% ========================================================================
% 9. Absolute net flux for logarithmic plotting
%
% Signed flux is retained for export.
% Absolute flux is used only for Figure 6 magnitude comparison.
% ========================================================================

pBasic = abs(vBasic);

pIsozyme = abs(vIsozyme);

pIntegrated = abs(vIntegrated);


%% ========================================================================
% 10. Log plotting range
% ========================================================================

allPlotFlux = [
    pBasic
    pIsozyme
    pIntegrated
];


minExp = floor( ...
    log10(min(allPlotFlux)));


maxExp = ceil( ...
    log10(max(allPlotFlux)));


logLimits = 10.^[ ...
    minExp ...
    maxExp];


% Major log ticks
if maxExp - minExp <= 10

    tickExp = minExp:maxExp;

else

    tickExp = minExp:2:maxExp;

end


logTicks = 10.^tickExp;


tickLabels = compose( ...
    '10^{%d}', ...
    tickExp);


%% ========================================================================
% 11. Figure style
% ========================================================================

FONT_NAME = 'Arial';

FONT_SIZE = 9;

AX_LINE_W = 0.9;

ID_LINE_W = 1.2;

MARKER_SZ = 25;
HILITE_SZ = 65;


% Main points: muted scientific blue
COLOR_MAIN = [
    0.22 ...
    0.46 ...
    0.69];


% Off-diagonal reactions: muted orange/red
COLOR_OUTLIER = [
    0.84 ...
    0.37 ...
    0.20];


% Identity line
COLOR_IDENTITY = [
    0.25 ...
    0.25 ...
    0.25];


% Major grid
COLOR_GRID = [
    0.80 ...
    0.80 ...
    0.80];


%% ========================================================================
% 12. Off-diagonal definition
% ========================================================================

% 1.2 = >=20% fold difference
% 2   = >=2-fold
% 3   = >=3-fold

foldThreshold = 1.2;


maxLabels2D = 6;

maxLabels3D = 8;


%% ========================================================================
% 13. 3D comparison
% ========================================================================

fig3 = figure( ...
    'Color', 'w', ...
    'Position', [100 80 800 700]);


ax3 = axes(fig3);

hold(ax3, 'on');


%% ------------------------------------------------------------------------
% Main 3D scatter
% -------------------------------------------------------------------------

scatter3( ...
    ax3, ...
    pBasic, ...
    pIsozyme, ...
    pIntegrated, ...
    MARKER_SZ, ...
    ...
    'MarkerFaceColor', COLOR_MAIN, ...
    'MarkerEdgeColor', 'none', ...
    'MarkerFaceAlpha', 0.65);


%% ------------------------------------------------------------------------
% Identity line x = y = z
% -------------------------------------------------------------------------

d = logspace( ...
    minExp, ...
    maxExp, ...
    400);


plot3( ...
    ax3, ...
    d, ...
    d, ...
    d, ...
    '--', ...
    ...
    'Color', COLOR_IDENTITY, ...
    'LineWidth', ID_LINE_W);


%% ------------------------------------------------------------------------
% 3D fold spread
%
% max flux among three models
% ---------------------------
% min flux among three models
% -------------------------------------------------------------------------

flux3D = [
    pBasic ...
    pIsozyme ...
    pIntegrated
];


maxFlux3D = max( ...
    flux3D, ...
    [], ...
    2);


minFlux3D = min( ...
    flux3D, ...
    [], ...
    2);


foldSpread3D = ...
    maxFlux3D ./ minFlux3D;


idx3DAll = find( ...
    foldSpread3D >= foldThreshold);


% Rank strongest deviations
[~, order3D] = sort( ...
    foldSpread3D(idx3DAll), ...
    'descend');


idx3DAll = idx3DAll(order3D);


idx3DLabel = idx3DAll( ...
    1:min( ...
        maxLabels3D, ...
        numel(idx3DAll)));


fprintf( ...
    '\n3D deviating reactions (>= %.2f-fold): %d\n', ...
    foldThreshold, ...
    numel(idx3DAll));


%% ------------------------------------------------------------------------
% Highlight 3D off-diagonal reactions
% -------------------------------------------------------------------------

if ~isempty(idx3DAll)

    scatter3( ...
        ax3, ...
        ...
        pBasic(idx3DAll), ...
        pIsozyme(idx3DAll), ...
        pIntegrated(idx3DAll), ...
        ...
        HILITE_SZ, ...
        ...
        'o', ...
        ...
        'MarkerEdgeColor', COLOR_OUTLIER, ...
        'MarkerFaceColor', 'w', ...
        ...
        'LineWidth', 1.1);

end


%% ------------------------------------------------------------------------
% Label strongest 3D off-diagonal parent reactions
% -------------------------------------------------------------------------

if ~isempty(idx3DLabel)

    for k = 1:numel(idx3DLabel)

        idx = idx3DLabel(k);


        switch mod(k-1, 6)

            case 0

                fx = 1.18;
                fy = 1.18;
                fz = 1.18;

            case 1

                fx = 1.18;
                fy = 0.84;
                fz = 1.18;

            case 2

                fx = 0.84;
                fy = 1.18;
                fz = 1.18;

            case 3

                fx = 1.18;
                fy = 1.18;
                fz = 0.84;

            case 4

                fx = 0.84;
                fy = 0.84;
                fz = 1.18;

            otherwise

                fx = 1.18;
                fy = 0.84;
                fz = 0.84;

        end


        text( ...
            ax3, ...
            ...
            pBasic(idx)      * fx, ...
            pIsozyme(idx)    * fy, ...
            pIntegrated(idx) * fz, ...
            ...
            commonRxns(idx), ...
            ...
            'FontName', FONT_NAME, ...
            'FontSize', FONT_SIZE - 1, ...
            ...
            'Interpreter', 'none', ...
            ...
            'Color', COLOR_OUTLIER, ...
            ...
            'HorizontalAlignment', 'left', ...
            'VerticalAlignment', 'middle');

    end

end


%% ------------------------------------------------------------------------
% 3D axes
% -------------------------------------------------------------------------

% 3D only: keep one major tick at every order of magnitude.
% Hide only the minor ticks between adjacent decades.
tickExp3D = minExp:maxExp;
logTicks3D = 10.^tickExp3D;
tickLabels3D = compose('10^{%d}', tickExp3D);

set( ...
    ax3, ...
    ...
    'XScale', 'log', ...
    'YScale', 'log', ...
    'ZScale', 'log', ...
    ...
    'XTick', logTicks3D, ...
    'YTick', logTicks3D, ...
    'ZTick', logTicks3D, ...
    ...
    'XTickLabel', tickLabels3D, ...
    'YTickLabel', tickLabels3D, ...
    'ZTickLabel', tickLabels3D, ...
    'XMinorTick', 'off', ...
    'YMinorTick', 'off', ...
    'ZMinorTick', 'off', ...
    ...
    'TickLabelInterpreter', 'tex', ...
    ...
    'FontName', FONT_NAME, ...
    'FontSize', FONT_SIZE + 3, ...
    ...
    'LineWidth', AX_LINE_W, ...
    'TickDir', 'out', ...
    ...
    'XColor', 'k', ...
    'YColor', 'k', ...
    'ZColor', 'k', ...
    ...
    'GridColor', COLOR_GRID, ...
    'GridAlpha', 0.55, ...
    'GridLineStyle', '-', ...
    ...
    'XGrid', 'on', ...
    'YGrid', 'on', ...
    'ZGrid', 'on', ...
    ...
    'XMinorGrid', 'off', ...
    'YMinorGrid', 'off', ...
    'ZMinorGrid', 'off', ...
    ...
    'Box', 'on', ...
    'Layer', 'top');


% Show opposite/back axes
if isprop(ax3, 'BoxStyle')

    ax3.BoxStyle = 'full';

end


% Scientific 3D appearance without perspective distortion
if isprop(ax3, 'Projection')

    ax3.Projection = 'orthographic';

end


xlim(ax3, logLimits);

ylim(ax3, logLimits);

zlim(ax3, logLimits);


xlabel( ...
    ax3, ...
    'Basic flux magnitude', ...
    ...
    'FontName', FONT_NAME, ...
    'FontSize', FONT_SIZE + 1);


ylabel( ...
    ax3, ...
    'Isozyme flux magnitude', ...
    ...
    'FontName', FONT_NAME, ...
    'FontSize', FONT_SIZE + 1);


zlabel( ...
    ax3, ...
    'Integrated flux magnitude', ...
    ...
    'FontName', FONT_NAME, ...
    'FontSize', FONT_SIZE + 1);


view( ...
    ax3, ...
    38, ...
    26);


%% ------------------------------------------------------------------------
% Export 3D
% -------------------------------------------------------------------------

print( ...
    fig3, ...
    fullfile(outputDir, 'Figure6_3D_flux_comparison.svg'), ...
    '-dsvg', ...
    '-painters');


%% ========================================================================
% 14. Pairwise 2D comparisons
% ========================================================================

fig2 = figure( ...
    'Color', 'w', ...
    'Position', [80 100 1380 450]);


layout = tiledlayout( ...
    fig2, ...
    1, ...
    3, ...
    ...
    'TileSpacing', 'compact', ...
    'Padding', 'compact');


%% ------------------------------------------------------------------------
% A. Basic vs Isozyme
% -------------------------------------------------------------------------

ax1 = nexttile(layout);


statsBI = plotPairNature( ...
    ax1, ...
    ...
    pBasic, ...
    pIsozyme, ...
    ...
    commonRxns, ...
    ...
    'Basic', ...
    'Isozyme', ...
    ...
    'a', ...
    ...
    minExp, ...
    maxExp, ...
    ...
    logTicks, ...
    tickLabels, ...
    ...
    foldThreshold, ...
    maxLabels2D, ...
    ...
    FONT_NAME, ...
    FONT_SIZE, ...
    AX_LINE_W, ...
    ID_LINE_W, ...
    MARKER_SZ, ...
    HILITE_SZ, ...
    ...
    COLOR_MAIN, ...
    COLOR_OUTLIER, ...
    COLOR_IDENTITY, ...
    COLOR_GRID);


%% ------------------------------------------------------------------------
% B. Basic vs Integrated
% -------------------------------------------------------------------------

ax2 = nexttile(layout);


statsBG = plotPairNature( ...
    ax2, ...
    ...
    pBasic, ...
    pIntegrated, ...
    ...
    commonRxns, ...
    ...
    'Basic', ...
    'Integrated', ...
    ...
    'b', ...
    ...
    minExp, ...
    maxExp, ...
    ...
    logTicks, ...
    tickLabels, ...
    ...
    foldThreshold, ...
    maxLabels2D, ...
    ...
    FONT_NAME, ...
    FONT_SIZE, ...
    AX_LINE_W, ...
    ID_LINE_W, ...
    MARKER_SZ, ...
    HILITE_SZ, ...
    ...
    COLOR_MAIN, ...
    COLOR_OUTLIER, ...
    COLOR_IDENTITY, ...
    COLOR_GRID);


%% ------------------------------------------------------------------------
% C. Isozyme vs Integrated
% -------------------------------------------------------------------------

ax3_2D = nexttile(layout);


statsIG = plotPairNature( ...
    ax3_2D, ...
    ...
    pIsozyme, ...
    pIntegrated, ...
    ...
    commonRxns, ...
    ...
    'Isozyme', ...
    'Integrated', ...
    ...
    'c', ...
    ...
    minExp, ...
    maxExp, ...
    ...
    logTicks, ...
    tickLabels, ...
    ...
    foldThreshold, ...
    maxLabels2D, ...
    ...
    FONT_NAME, ...
    FONT_SIZE, ...
    AX_LINE_W, ...
    ID_LINE_W, ...
    MARKER_SZ, ...
    HILITE_SZ, ...
    ...
    COLOR_MAIN, ...
    COLOR_OUTLIER, ...
    COLOR_IDENTITY, ...
    COLOR_GRID);


%% ------------------------------------------------------------------------
% Export 2D figure
% -------------------------------------------------------------------------
print( ...
    fig2, ...
    fullfile(outputDir, 'Figure6_pairwise_2D_flux_comparison.svg'), ...
    '-dsvg', ...
    '-painters');


%% ========================================================================
% 15. Export aligned flux table
% ========================================================================

fluxTable = table( ...
    ...
    commonRxns, ...
    ...
    vBasic, ...
    vIsozyme, ...
    vIntegrated, ...
    ...
    pBasic, ...
    pIsozyme, ...
    pIntegrated, ...
    ...
    foldSpread3D, ...
    ...
    'VariableNames', { ...
        'ReactionID', ...
        ...
        'Basic_NetFlux', ...
        'Isozyme_NetFlux', ...
        'Integrated_NetFlux', ...
        ...
        'Basic_AbsFlux', ...
        'Isozyme_AbsFlux', ...
        'Integrated_AbsFlux', ...
        ...
        'ThreeD_FoldSpread'});


writetable( ...
    fluxTable, ...
    fullfile(outputDir, 'Figure6_aligned_fluxes.xlsx'));


%% ========================================================================
% 16. Export correlation summary
% ========================================================================

summaryTable = table( ...
    ...
    { ...
    'Basic vs Isozyme'; ...
    'Basic vs Integrated'; ...
    'Isozyme vs Integrated'}, ...
    ...
    [ ...
    statsBI.n; ...
    statsBG.n; ...
    statsIG.n], ...
    ...
    [ ...
    statsBI.pearson_r; ...
    statsBG.pearson_r; ...
    statsIG.pearson_r], ...
    ...
    [ ...
    statsBI.R2; ...
    statsBG.R2; ...
    statsIG.R2], ...
    ...
    [ ...
    statsBI.spearman_rho; ...
    statsBG.spearman_rho; ...
    statsIG.spearman_rho], ...
    ...
    [ ...
    statsBI.nDeviating; ...
    statsBG.nDeviating; ...
    statsIG.nDeviating], ...
    ...
    'VariableNames', { ...
        'Comparison', ...
        'n', ...
        'Pearson_r_log10', ...
        'R2_log10', ...
        'Spearman_rho_log10', ...
        'DeviatingReactions'});


writetable( ...
    summaryTable, ...
    fullfile(outputDir, 'Figure6_correlation_summary.xlsx'));


fprintf('\nPairwise correlation summary:\n');

disp(summaryTable);


fprintf( ...
    '\n3D deviating reactions: %d / %d\n', ...
    numel(idx3DAll), ...
    numel(commonRxns));


fprintf('\nFigure 6 analysis completed.\n');


%% ========================================================================
% LOCAL FUNCTION 1
% Restore parent reaction net flux
% ========================================================================

function T = aggregateEcFlux(model, flux)

    rxns = string( ...
        model.rxns(:));

    flux = flux(:);


    %% --------------------------------------------------------------------
    % Remove protein bookkeeping reactions
    % ---------------------------------------------------------------------

    keep = ...
        ~startsWith(rxns, "usage_prot_") & ...
        ~startsWith(rxns, "draw_prot_") & ...
        rxns ~= "prot_pool_exchange";


    rxns = rxns(keep);

    flux = flux(keep);


    %% --------------------------------------------------------------------
    % Remove isozyme expansion suffix
    %
    % r_1138_EXP_1
    %       ->
    % r_1138
    %
    % r_1138_REV_EXP_2
    %       ->
    % r_1138_REV
    % ---------------------------------------------------------------------

    baseRxns = regexprep( ...
        rxns, ...
        '_EXP_[0-9]+$', ...
        '');


    %% --------------------------------------------------------------------
    % Detect irreversible reverse copies
    % ---------------------------------------------------------------------

    isReverse = endsWith( ...
        baseRxns, ...
        "_REV");


    %% --------------------------------------------------------------------
    % Reverse reaction contributes negatively to parent reaction
    % ---------------------------------------------------------------------

    signedFlux = flux;


    signedFlux(isReverse) = ...
        -signedFlux(isReverse);


    %% --------------------------------------------------------------------
    % Remove _REV
    %
    % r_1138_REV -> r_1138
    % ---------------------------------------------------------------------

    baseRxns = regexprep( ...
        baseRxns, ...
        '_REV$', ...
        '');


    %% --------------------------------------------------------------------
    % Remove possible bookkeeping prefix
    %
    % 001_r_1138 -> r_1138
    % ---------------------------------------------------------------------

    baseRxns = regexprep( ...
        baseRxns, ...
        '^[0-9]{3}_', ...
        '');


    %% --------------------------------------------------------------------
    % Aggregate all copies to parent reaction
    % ---------------------------------------------------------------------

    [uniqueRxns, ~, group] = unique( ...
        baseRxns, ...
        'stable');


    netFlux = accumarray( ...
        group, ...
        signedFlux, ...
        [], ...
        @sum);


    %% --------------------------------------------------------------------
    % Output
    % ---------------------------------------------------------------------

    T = table( ...
        uniqueRxns, ...
        netFlux, ...
        ...
        'VariableNames', { ...
            'ReactionID', ...
            'NetFlux'});

end


%% ========================================================================
% LOCAL FUNCTION 2
% Pairwise Nature-style log-log comparison
% ========================================================================

function stats = plotPairNature( ...
    ax, ...
    ...
    x, ...
    y, ...
    ...
    rxnIDs, ...
    ...
    xName, ...
    yName, ...
    ...
    panelLabel, ...
    ...
    minExp, ...
    maxExp, ...
    ...
    logTicks, ...
    tickLabels, ...
    ...
    foldThreshold, ...
    maxLabels, ...
    ...
    FONT_NAME, ...
    FONT_SIZE, ...
    AX_LINE_W, ...
    ID_LINE_W, ...
    MARKER_SZ, ...
    HILITE_SZ, ...
    ...
    COLOR_MAIN, ...
    COLOR_OUTLIER, ...
    COLOR_IDENTITY, ...
    COLOR_GRID)


    hold(ax, 'on');


    %% --------------------------------------------------------------------
    % Main scatter
    % ---------------------------------------------------------------------

    scatter( ...
        ax, ...
        ...
        x, ...
        y, ...
        ...
        MARKER_SZ, ...
        ...
        'MarkerFaceColor', COLOR_MAIN, ...
        'MarkerEdgeColor', 'none', ...
        'MarkerFaceAlpha', 0.70);


    %% --------------------------------------------------------------------
    % Identity line
    % ---------------------------------------------------------------------

    d = logspace( ...
        minExp, ...
        maxExp, ...
        400);


    plot( ...
        ax, ...
        ...
        d, ...
        d, ...
        ...
        '--', ...
        ...
        'Color', COLOR_IDENTITY, ...
        'LineWidth', ID_LINE_W);


    %% --------------------------------------------------------------------
    % Axis formatting
    % ---------------------------------------------------------------------

    set( ...
        ax, ...
        ...
        'XScale', 'log', ...
        'YScale', 'log', ...
        ...
        'XTick', logTicks, ...
        'YTick', logTicks, ...
        ...
        'XTickLabel', tickLabels, ...
        'YTickLabel', tickLabels, ...
        ...
        'TickLabelInterpreter', 'tex', ...
        ...
        'FontName', FONT_NAME, ...
        'FontSize', FONT_SIZE, ...
        ...
        'LineWidth', AX_LINE_W, ...
        'TickDir', 'out', ...
        ...
        'Box', 'off', ...
        ...
        'XColor', 'k', ...
        'YColor', 'k', ...
        ...
        'GridColor', COLOR_GRID, ...
        'GridAlpha', 0.50, ...
        'GridLineStyle', '-', ...
        ...
        'XGrid', 'on', ...
        'YGrid', 'on', ...
        ...
        'XMinorGrid', 'off', ...
        'YMinorGrid', 'off');


    limits = 10.^[ ...
        minExp ...
        maxExp];


    xlim(ax, limits);

    ylim(ax, limits);


    axis( ...
        ax, ...
        'square');


    xlabel( ...
        ax, ...
        [xName ' flux magnitude'], ...
        ...
        'FontName', FONT_NAME, ...
        'FontSize', FONT_SIZE + 1);


    ylabel( ...
        ax, ...
        [yName ' flux magnitude'], ...
        ...
        'FontName', FONT_NAME, ...
        'FontSize', FONT_SIZE + 1);


    %% --------------------------------------------------------------------
    % Correlation in log10 space
    % ---------------------------------------------------------------------

    lx = log10(x);

    ly = log10(y);


    P = corrcoef( ...
        lx, ...
        ly);


    if numel(P) == 4

        pearson_r = P(1,2);

    else

        pearson_r = NaN;

    end


    if numel(lx) > 1

        spearman_rho = corr( ...
            lx, ...
            ly, ...
            ...
            'Type', ...
            'Spearman');

    else

        spearman_rho = NaN;

    end


    R2 = pearson_r^2;

    n = numel(x);


    %% --------------------------------------------------------------------
    % Pairwise fold difference
    % ---------------------------------------------------------------------

    foldDifference = max( ...
        y ./ x, ...
        x ./ y);


    idxAll = find( ...
        foldDifference >= foldThreshold);


    % Strongest deviations first
    [~, order] = sort( ...
        foldDifference(idxAll), ...
        'descend');


    idxAll = idxAll(order);


    idxLabel = idxAll( ...
        1:min( ...
            maxLabels, ...
            numel(idxAll)));


    %% --------------------------------------------------------------------
    % Highlight all off-diagonal reactions
    % ---------------------------------------------------------------------

    if ~isempty(idxAll)

        scatter( ...
            ax, ...
            ...
            x(idxAll), ...
            y(idxAll), ...
            ...
            HILITE_SZ, ...
            ...
            'o', ...
            ...
            'MarkerEdgeColor', COLOR_OUTLIER, ...
            'MarkerFaceColor', 'w', ...
            ...
            'LineWidth', 1.0);

    end


    %% --------------------------------------------------------------------
    % Annotate strongest parent reactions
    % ---------------------------------------------------------------------

    if ~isempty(idxLabel)

        for k = 1:numel(idxLabel)

            idx = idxLabel(k);


            if mod(k,2) == 1

                fx = 1.12;
                fy = 1.12;

            else

                fx = 1.12;
                fy = 0.88;

            end


            text( ...
                ax, ...
                ...
                x(idx) * fx, ...
                y(idx) * fy, ...
                ...
                rxnIDs(idx), ...
                ...
                'FontName', FONT_NAME, ...
                'FontSize', FONT_SIZE - 1, ...
                ...
                'Interpreter', 'none', ...
                ...
                'Color', COLOR_OUTLIER, ...
                ...
                'HorizontalAlignment', 'left', ...
                'VerticalAlignment', 'middle');

        end

    end


    %% --------------------------------------------------------------------
    % Panel label
    % ---------------------------------------------------------------------

    text( ...
        ax, ...
        ...
        -0.13, ...
        1.07, ...
        ...
        panelLabel, ...
        ...
        'Units', 'normalized', ...
        ...
        'FontName', FONT_NAME, ...
        'FontSize', FONT_SIZE + 3, ...
        'FontWeight', 'bold', ...
        ...
        'HorizontalAlignment', 'left', ...
        'VerticalAlignment', 'bottom', ...
        ...
        'Color', 'k');


    %% --------------------------------------------------------------------
    % Statistics
    % ---------------------------------------------------------------------

    statsText = { ...
        sprintf('r = %.3f', pearson_r)
        sprintf('R^2 = %.3f', R2)
        sprintf('\\rho = %.3f', spearman_rho)
        sprintf('n = %d', n)
        };


    text( ...
        ax, ...
        ...
        0.05, ...
        0.95, ...
        ...
        statsText, ...
        ...
        'Units', 'normalized', ...
        ...
        'FontName', FONT_NAME, ...
        'FontSize', FONT_SIZE, ...
        ...
        'VerticalAlignment', 'top', ...
        'HorizontalAlignment', 'left', ...
        ...
        'Interpreter', 'tex', ...
        ...
        'Color', 'k');


    %% --------------------------------------------------------------------
    % Return statistics
    % ---------------------------------------------------------------------

    stats = struct();


    stats.pearson_r = pearson_r;

    stats.R2 = R2;

    stats.spearman_rho = spearman_rho;

    stats.n = n;

    stats.nDeviating = numel(idxAll);

end