function codes = bridge_error_catalogue()
%BRIDGE_ERROR_CATALOGUE The canonical 14 codes, also enforced in Python.
    codes = { 'err_init_fail',  'err_param_invalid',  'err_model_format',  ...
              'err_no_biomass', 'err_no_target',      'err_docker_missing',...
              'err_no_proteomics','err_gurobi_license','err_raven_notfound',...
              'err_sluice_data','err_kcat_merge',     'err_presto_data',   ...
              'err_oom',        'err_cancelled' };
end