function payload = make_ok(result)
%MAKE_OK Build a success envelope. result may be any JSON-serialisable value.
    payload = struct('ok', true, ...
                     'error_code', '', ...
                     'error_message', '', ...
                     'result', result);
end